name: 'Trigger and Close ServiceNow Change Control'
description: 'Triggers and optionally closes a Change Control in ServiceNow for automated deployments.'

inputs:
  SN_INSTANCE_URL:
    description: 'ServiceNow instance URL.'
    required: true
  SN_USERNAME:
    description: 'ServiceNow DevOps integration username.'
    required: true
  SN_PASSWORD:
    description: 'ServiceNow DevOps integration password.'
    required: true
  SN_ORCHESTRATION_TOOL_ID:
    description: 'ServiceNow Orchestration Tool ID.'
    required: true
  job-name:
    description: 'The name of the GitHub job triggering the change.'
    required: true
    default: 'prod-deploy'
  short-description:
    description: 'Short description of the change request.'
    required: true
  description:
    description: 'Detailed description of the change request.'
    required: true
  implementation-plan:
    description: 'Implementation plan for the change request.'
    required: true
  backout-plan:
    description: 'Backout plan.'
    required: true
  test-plan:
    description: 'Test plan.'
    required: true
  assignment-group:
    description: 'The ServiceNow assignment group sys_id'
    required: true
  assigned-to:
    description: 'The ServiceNow user sys_id to whom the CHG is assigned'
    required: false
  work-notes:
    description: 'The status of the actual GitHub deployment'
    required: false
  context-github:
    description: 'GitHub context.'
    required: true
  actual_start_date:
    description: 'UTC ISO timestamp for when change actually started.'
    required: false
  actual_end_date:
    description: 'UTC ISO timestamp for when change actually ended.'
    required: false
  deploy_status:
    description: 'Deployment status (success/failure).'
    required: false
  auto-close:
    description: 'Whether to auto-close the change after creation.'
    required: false
    default: 'false'

outputs:
  change_request_number:
    description: 'The created Change Request number'
  change_request_sys_id:
    description: 'The created Change Request sys_id'
  change_request_url:
    description: 'URL to view the created Change Request'

runs:
  using: "composite"
  steps:
    - name: Generate change-request JSON safely
      shell: bash
      run: |
        CHANGE_REQUEST_JSON=$(jq -n \
          --arg short_description "${{ inputs.short-description }}" \
          --arg description "${{ inputs.description }}" \
          --arg implementation_plan "${{ inputs['implementation-plan'] }}" \
          --arg backout_plan "${{ inputs['backout-plan'] }}" \
          --arg test_plan "${{ inputs['test-plan'] }}" \
          --arg assignment_group "${{ inputs['assignment-group'] }}" \
          --arg assigned_to "${{ inputs['assigned-to'] }}" \
          --arg work_notes "${{ inputs['work-notes'] }}" \
          '{
            autoCloseChange: "true",
            attributes: {
              short_description: $short_description,
              description: $description,
              implementation_plan: $implementation_plan,
              backout_plan: $backout_plan,
              test_plan: $test_plan,
              assignment_group: $assignment_group,
              assigned_to: $assigned_to,
              work_notes: $work_notes
            }
          }')
        echo "$CHANGE_REQUEST_JSON" > change_request.json
        echo "CHANGE_REQUEST_JSON<<EOF" >> $GITHUB_ENV
        echo "$CHANGE_REQUEST_JSON" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Trigger Change Control in ServiceNow
      uses: ServiceNow/servicenow-devops-change@v6.0.0
      id: change_creation
      with:
        instance-url: ${{ inputs.SN_INSTANCE_URL }}
        devops-integration-user-name: ${{ inputs.SN_USERNAME }}
        devops-integration-user-password: ${{ inputs.SN_PASSWORD }}
        tool-id: ${{ inputs.SN_ORCHESTRATION_TOOL_ID }}
        context-github: ${{ inputs.context-github }}
        job-name: ${{ inputs.job-name }}
        change-request: ${{ env.CHANGE_REQUEST_JSON }}

    - name: Expose outputs
      shell: bash
      run: |
        echo "change_request_number=${{ steps.change_creation.outputs.change_request_number }}" >> $GITHUB_OUTPUT
        echo "change_request_sys_id=${{ steps.change_creation.outputs.change_request_sys_id }}" >> $GITHUB_OUTPUT
        echo "change_request_url=${{ steps.change_creation.outputs.change_request_url }}" >> $GITHUB_OUTPUT

    - name: Auto-close change
      if: ${{ inputs.auto-close == 'true' && inputs.actual_start_date != '' && inputs.actual_end_date != '' }}
      shell: bash
      run: |
        SYS_ID="${{ steps.change_creation.outputs.change_request_sys_id }}"
        echo "Closing change request $SYS_ID in ServiceNow..."
        curl -s -X PATCH \
          "${{ inputs.SN_INSTANCE_URL }}/api/sn_devops/devops/change/${SYS_ID}" \
          --user "${{ inputs.SN_USERNAME }}:${{ inputs.SN_PASSWORD }}" \
          --header "Content-Type: application/json" \
          --data "{
            \"actual_start_date\": \"${{ inputs.actual_start_date }}\",
            \"actual_end_date\": \"${{ inputs.actual_end_date }}\",
            \"close_code\": \"${{ inputs.deploy_status }}\",
            \"state\": \"${{ inputs.deploy_status }}\" == \"success\" ? \"closed_successful\" : \"closed_incomplete\",
            \"work_notes\": \"GitHub deployment result: ${{ inputs.deploy_status }}\"
          }"
        echo "Change request closed."
