name: 'Trigger ServiceNow Change Control'
description: 'Triggers a Change Control in ServiceNow for automated deployments.'

inputs:
  SN_INSTANCE_URL:
    description: 'ServiceNow instance URL.'
    required: true
  SN_USERNAME:
    description: 'ServiceNow DevOps integration username.'
    required: true
  SN_PASSWORD:
    description: 'ServiceNow DevOps integration password.'
    required: true
  SN_ORCHESTRATION_TOOL_ID:
    description: 'ServiceNow Orchestration Tool ID.'
    required: true
  job-name:
    description: 'The name of the GitHub job triggering the change.'
    required: true
    default: 'prod-deploy'
  short-description:
    description: 'Short description for the Change Request.'
    required: true
  description:
    description: 'Detailed description for the Change Request.'
    required: true
  implementation-plan:
    description: 'Implementation plan.'
    required: true
  backout-plan:
    description: 'Backout plan.'
    required: true
  test-plan:
    description: 'Test plan.'
    required: true
  context-github:
    description: 'GitHub context.'
    required: true

outputs:
  change_request_number:
    description: 'The created Change Request number'
    value: ${{ steps.change_creation.outputs.change_request_number }}
  change_request_sys_id:
    description: 'The created Change Request sys_id'
    value: ${{ steps.change_creation.outputs.change_request_sys_id }}
  change_request_url:
    description: 'URL to view the created Change Request'
    value: ${{ steps.change_creation.outputs.change_request_url }}

runs:
  using: "composite"
  steps:
    - name: Trigger Change Control in ServiceNow
      uses: ServiceNow/servicenow-devops-change@v6.0.0
      id: change_creation
      with:
        instance-url: ${{ inputs.SN_INSTANCE_URL }}
        devops-integration-user-name: ${{ inputs.SN_USERNAME }}
        devops-integration-user-password: ${{ inputs.SN_PASSWORD }}
        tool-id: ${{ inputs.SN_ORCHESTRATION_TOOL_ID }}
        context-github: ${{ inputs.context-github }}
        job-name: ${{ inputs.job-name }}
        change-request: >-
          {
            "setCloseCode": "true",
            "autoCloseChange": true,
            "attributes": {
              "short_description": "${{ inputs.short-description }}",
              "description": "${{ inputs.description }}",
              "implementation_plan": "${{ inputs.implementation-plan }}",
              "backout_plan": "${{ inputs.backout-plan }}",
              "test_plan": "${{ inputs.test-plan }}",
              "assignment_group": "Change-Velocity-Group",
              "assigned_to": "Steven LaPlante",
              "displayValue": true
          }
        }

    - name: Debug outputs from ServiceNow step
      run: |
        echo "DEBUG: CR Number => ${{ steps.change_creation.outputs.change_request_number }}"
        echo "DEBUG: CR Sys ID => ${{ steps.change_creation.outputs.change_request_sys_id }}"
        echo "DEBUG: CR URL    => ${{ steps.change_creation.outputs.change_request_url }}"
      shell: bash
